### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by paoloantinori** [bytrangle/gdrive-search#1]
```
10:10 $ bin/godri.js authorize
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '../lib/oAuth2Client'
Require stack:
- /data/repo/apps/gdrive-search/commands/auth.js
- /data/repo/apps/gdrive-search/bin/godri.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/repo/apps/gdrive-search/commands/auth.js:5:26)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/repo/apps/gdrive-search/commands/auth.js',
    '/data/repo/apps/gdrive-search/bin/godri.js'
  ]
}
```

And there is actually no such module checked in with the project.

**Comment by paoloantinori** [comment]
reverting to this commit works: `d2ef71a8ade7890cadf353dfca7b457fef4fdfd6`

And please consider providing guidance on the env variables required to activate this =)

```
10:50 $ export REDIRECT_URI='http://localhost'  CLIENT_ID='XXXXXXXXXXXXX' CLIENT_SECRET='YYYYYYY' && bin/godri.js authorize
```

thanks for your project!

**Comment by bytrangle** [comment]
@paoloantinori API requests to Google Drive are made through Google API client.  Constructing this client requires client ID, client secret and redirect uris. Where do you suggest. These values are different between users. Where do you suggest I should store them?

**Comment by paoloantinori** [comment]
HI Trang, I'm fine with the idea of having this in independent files.

But what I was reporting is that the current `master` branch, if used on a system that has not preconfigured secrets, just fails.

The specific commit I've list instead, does not fail.

**Comment by bytrangle** [comment]
@paoloantinori I'm fixing it now.
